export const INTIAILIZE_APP = 'INITIALIZE_APP'
export const KEYBOARD_UP = 'KEYBOARD_UP'

export const COMPOSE_TEXT_INPUT = 'COMPOSE_TEXT_INPUT'

export const ADD_MESSAGES = 'ADD_MESSAGES'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'
export const DELETE_MESSAGES = 'DELETE_MESSAGES'

export const USER_ADDRESS = 'USER_ADDRESS'
export const USER_EMAIL = 'USER_EMAIL'
export const USER_FIRSTNAME = 'USER_FIRSTNAME'
export const USER_LASTNAME = 'USER_LASTNAME'
