export const INTIAILIZE_APP = 'INITIALIZE_APP'

export const COMPOSE_TEXT_INPUT = 'COMPOSE_TEXT_INPUT'

export const ADD_MESSAGES = 'ADD_MESSAGES'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'
export const DELETE_MESSAGES = 'DELETE_MESSAGES'
