export const INITIALIZATION = 'INITIALIZATION'
export const KEYBOARD_UP = 'KEYBOARD_UP'
export const NAVIGATE = 'NAVIGATE'

export const COMPOSE_TEXT_INPUT = 'COMPOSE_TEXT_INPUT'

export const ADD_MESSAGES = 'ADD_MESSAGES'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'
export const DELETE_MESSAGES = 'DELETE_MESSAGES'

export const ADD_MEMBERS = 'ADD_MEMBERS'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const USER_REGISTER = 'USER_REGISTER'
