import { isSmallScreen } from 'utils/helpers'
import C from './colors.style'
import E from './element.style'
import F from './font.style'

const DARK_MODE = true

export default {
  DARK_MODE: DARK_MODE,

  // Colors
  BACKGROUND_COLOR: DARK_MODE ? C.DARK_BACKGROUND : C.LIGHT_BACKGROUND,
  FOREGROUND_COLOR: DARK_MODE ? C.DARK_FOREGROUND : C.LIGHT_FOREGROUND,
  PRIMARY_COLOR: DARK_MODE ? C.DARK_PRIMARY : C.LIGHT_PRIMARY,
  INVERSE_COLOR: DARK_MODE ? C.DARK_INVERSE : C.LIGHT_INVERSE,
  INPUT_PLACEHOLDER: DARK_MODE ? C.DARK_INPUT_PLACEHOLDER : C.LIGHT_INPUT_PLACEHOLDER,
  WHITE: C.WHITE,
  BLACK: C.BLACK,
  BRAND_COLOR: C.BRAND_COLOR,
  OPAQUE_BRAND: C.OPAQUE_BRAND,
  PENDING: C.BRAND_COLOR,
  VALID: C.VALID_GREEN,
  INVALID: C.INVALID_RED,

  // Fonts
  FONT_BODY: F.HELVETICA,
  FONT_TITLE: F.COCOGOOSE,
  FONT_SMALL: isSmallScreen ? F.EXTRA_SMALL : F.SMALL,
  FONT_MEDIUM: isSmallScreen ? F.MEDIUM : F.SMALL,
  FONT_LARGE: isSmallScreen ? F.LARGE : F.MEDIUM,

  // Element Sizing
  LOGO_DIAMETER: isSmallScreen ? E.LOGO_SMALL:  E.LOGO_LARGE,
  MODAL_RADIUS: E.MODAL_RADIUS,
  PILL_BUTTON_RADIUS: E.PILL_BUTTON_RADIUS,
  SPINNER_RADIUS: E.SPINNER_RADIUS
}
